"""
База питань по мовах.
QUESTIONS[мова][складність] — для звичайних режимів
INFINITE_QUESTIONS[мова] — тільки для нескінченного режиму (100 питань)
correct: індекс правильної відповіді (0=A, 1=B, 2=C, 3=D)
"""

def _default(label, count):
    return [
        {"q": f"Default Text — {label} {i}?",
         "a": ["Default A", "Default B", "Default C", "Default D"],
         "correct": (i - 1) % 4}
        for i in range(1, count + 1)
    ]

# ═══════════════════════════════════════════════════════════════
#  ЗВИЧАЙНІ РЕЖИМИ
# ═══════════════════════════════════════════════════════════════
QUESTIONS = {

    # ── УКРАЇНСЬКА ───────────────────────────────────────────
    "uk": {
        "easy":   _default("Легке питання", 10),
        "medium": _default("Середнє питання", 20),
        "hard":   _default("Важке питання", 30),
    },

    # ── РУССКИЙ ──────────────────────────────────────────────
    "ru": {
        "easy": [
            {"q": "Какая столица России?", "a": ["Санкт-Петербург","Москва","Новосибирск","Казань"], "correct": 1},
            {"q": "Сколько дней в неделе?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Какая самая большая планета?", "a": ["Земля","Марс","Юпитер","Сатурн"], "correct": 2},
            {"q": "Сколько цветов у радуги?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Какой самый большой океан?", "a": ["Атлантический","Индийский","Арктический","Тихий"], "correct": 3},
            {"q": "Сколько месяцев в году?", "a": ["10","11","12","13"], "correct": 2},
            {"q": "Какая самая высокая гора в мире?", "a": ["К2","Канченджанга","Эверест","Макалу"], "correct": 2},
            {"q": "Какая столица Франции?", "a": ["Берлин","Мадрид","Рим","Париж"], "correct": 3},
            {"q": "Сколько часов в сутках?", "a": ["12","20","24","48"], "correct": 2},
            {"q": "Какое самое большое животное на Земле?", "a": ["Слон","Синий кит","Акула","Жираф"], "correct": 1},
        ],
        "medium": [
            {"q": "Какая самая длинная река в мире?", "a": ["Амазонка","Нил","Янцзы","Миссисипи"], "correct": 1},
            {"q": "Какая химическая формула воды?", "a": ["CO2","H2O","O2","NaCl"], "correct": 1},
            {"q": "В каком году началась Вторая мировая война?", "a": ["1937","1938","1939","1940"], "correct": 2},
            {"q": "Сколько игроков в футбольной команде?", "a": ["9","10","11","12"], "correct": 2},
            {"q": "Какая страна самая большая по площади?", "a": ["США","Китай","Канада","Россия"], "correct": 3},
            {"q": "Кто нарисовал 'Мона Лиза'?", "a": ["Микеланджело","Рафаэль","Леонардо да Винчи","Боттичелли"], "correct": 2},
            {"q": "Какая самая маленькая страна в мире?", "a": ["Монако","Ватикан","Сан-Марино","Лихтенштейн"], "correct": 1},
            {"q": "Сколько костей у взрослого человека?", "a": ["186","206","226","246"], "correct": 1},
            {"q": "Какая планета ближайшая к Солнцу?", "a": ["Венера","Земля","Меркурий","Марс"], "correct": 2},
            {"q": "В каком городе находится Колизей?", "a": ["Афины","Рим","Мадрид","Париж"], "correct": 1},
            {"q": "Кто был первым президентом США?", "a": ["Авраам Линкольн","Томас Джефферсон","Джон Адамс","Джордж Вашингтон"], "correct": 3},
            {"q": "Какова скорость света (приблизительно)?", "a": ["200 000 км/с","300 000 км/с","400 000 км/с","500 000 км/с"], "correct": 1},
            {"q": "Сколько хромосом у здорового человека?", "a": ["23","44","46","48"], "correct": 2},
            {"q": "Какая столица Австралии?", "a": ["Сидней","Мельбурн","Брисбен","Канберра"], "correct": 3},
            {"q": "Какой химический символ железа?", "a": ["Fe","Zn","Ir","In"], "correct": 0},
            {"q": "Какой орган вырабатывает инсулин?", "a": ["Печень","Почки","Поджелудочная железа","Селезёнка"], "correct": 2},
            {"q": "В каком году Россия запустила первый спутник?", "a": ["1955","1957","1959","1961"], "correct": 1},
            {"q": "Сколько нот в музыкальной гамме?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Какая самая глубокая точка океана?", "a": ["Жёлоб Пуэрто-Рико","Марианская впадина","Жёлоб Тонга","Жёлоб Филиппин"], "correct": 1},
            {"q": "Кто написал 'Преступление и наказание'?", "a": ["Лев Толстой","Антон Чехов","Иван Тургенев","Фёдор Достоевский"], "correct": 3},
        ],
        "hard": [
            {"q": "Какой элемент имеет атомный номер 79?", "a": ["Серебро","Платина","Золото","Медь"], "correct": 2},
            {"q": "Кто автор теории относительности?", "a": ["Исаак Ньютон","Нильс Бор","Альберт Эйнштейн","Макс Планк"], "correct": 2},
            {"q": "Кто был первым космонавтом в открытом космосе?", "a": ["Юрий Гагарин","Алексей Леонов","Герман Титов","Валентина Терешкова"], "correct": 1},
            {"q": "Кто доказал последнюю теорему Ферма?", "a": ["Карл Гаусс","Эндрю Уайлс","Анри Пуанкаре","Леонард Эйлер"], "correct": 1},
            {"q": "Сколько квантовых чисел описывают состояние электрона?", "a": ["2","3","4","5"], "correct": 2},
            {"q": "В каком году произошла Французская революция?", "a": ["1776","1783","1789","1799"], "correct": 2},
            {"q": "Какая самая маленькая кость в теле человека?", "a": ["Фаланга","Стремечко","Ключица","Запястная"], "correct": 1},
            {"q": "Кто открыл пенициллин?", "a": ["Луи Пастер","Роберт Кох","Александр Флеминг","Джозеф Листер"], "correct": 2},
            {"q": "Какой химический символ золота?", "a": ["Ag","Pt","Au","Cu"], "correct": 2},
            {"q": "Сколько симфоний написал Бетховен?", "a": ["7","8","9","10"], "correct": 2},
            {"q": "Какое расстояние от Земли до Луны (приблизительно)?", "a": ["184 000 км","284 000 км","384 000 км","484 000 км"], "correct": 2},
            {"q": "Кто является автором 'Илиады' и 'Одиссеи'?", "a": ["Вергилий","Гесиод","Гомер","Эзоп"], "correct": 2},
            {"q": "Какая формула серной кислоты?", "a": ["HCl","HNO3","H2SO4","H3PO4"], "correct": 2},
            {"q": "Какая самая высокая точка Африки?", "a": ["Гора Кения","Килиманджаро","Рас-Дашен","Монт-Мару"], "correct": 1},
            {"q": "Кто написал 'Фауст'?", "a": ["Шиллер","Гейне","Гёте","Кафка"], "correct": 2},
            {"q": "Какое самое глубокое озеро в мире?", "a": ["Каспийское","Байкал","Танганьика","Верхнее"], "correct": 1},
            {"q": "Кто является автором теории эволюции?", "a": ["Грегор Мендель","Жан-Батист Ламарк","Чарльз Дарвин","Томас Хаксли"], "correct": 2},
            {"q": "Сколько элементов в таблице Менделеева?", "a": ["112","116","118","120"], "correct": 2},
            {"q": "Какой закон описывает зависимость давления и объёма газа?", "a": ["Закон Шарля","Закон Гей-Люссака","Закон Бойля-Мариотта","Закон Авогадро"], "correct": 2},
            {"q": "Кто разработал первую вакцину против оспы?", "a": ["Луи Пастер","Эдвард Дженнер","Роберт Кох","Иван Мечников"], "correct": 1},
            {"q": "Какая самая холодная температура зафиксирована на Земле?", "a": ["-79°C","-89°C","-99°C","-109°C"], "correct": 1},
            {"q": "Какой орган отвечает за равновесие?", "a": ["Кора","Мозжечок","Гиппокамп","Таламус"], "correct": 1},
            {"q": "В каком веке жил Леонардо да Винчи?", "a": ["XIV","XV","XVI","XVII"], "correct": 1},
            {"q": "Кто написал 'Божественную комедию'?", "a": ["Петрарка","Боккаччо","Данте Алигьери","Ариосто"], "correct": 2},
            {"q": "Какое количество бит в одном байте?", "a": ["4","6","8","16"], "correct": 2},
            {"q": "Кто написал симфонию №9 с 'Одой к радости'?", "a": ["Моцарт","Шуберт","Бетховен","Гайдн"], "correct": 2},
            {"q": "Какая страна имеет больше всего озёр?", "a": ["Финляндия","Россия","Канада","США"], "correct": 2},
            {"q": "Кто является автором картины 'Звёздная ночь'?", "a": ["Поль Гоген","Клод Моне","Винсент ван Гог","Поль Сезанн"], "correct": 2},
            {"q": "Какая самая большая железа в теле человека?", "a": ["Поджелудочная","Щитовидная","Печень","Селезёнка"], "correct": 2},
            {"q": "В каком городе состоялись Олимпийские игры 1936 года?", "a": ["Лондон","Париж","Берлин","Рим"], "correct": 2},
        ],
    },

    # ── ENGLISH ──────────────────────────────────────────────
    "en": {
        "easy": [
            {"q": "What is the capital of England?", "a": ["Manchester","Birmingham","London","Liverpool"], "correct": 2},
            {"q": "How many days are in a week?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Which is the largest planet?", "a": ["Earth","Mars","Jupiter","Saturn"], "correct": 2},
            {"q": "How many colors are in a rainbow?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Which is the largest ocean?", "a": ["Atlantic","Indian","Arctic","Pacific"], "correct": 3},
            {"q": "How many months are in a year?", "a": ["10","11","12","13"], "correct": 2},
            {"q": "What is the tallest mountain in the world?", "a": ["K2","Kangchenjunga","Everest","Makalu"], "correct": 2},
            {"q": "What is the capital of France?", "a": ["Berlin","Madrid","Rome","Paris"], "correct": 3},
            {"q": "How many hours are in a day?", "a": ["12","20","24","48"], "correct": 2},
            {"q": "What is the largest animal on Earth?", "a": ["Elephant","Blue whale","Shark","Giraffe"], "correct": 1},
        ],
        "medium": [
            {"q": "What is the longest river in the world?", "a": ["Amazon","Nile","Yangtze","Mississippi"], "correct": 1},
            {"q": "What is the chemical formula for water?", "a": ["CO2","H2O","O2","NaCl"], "correct": 1},
            {"q": "In what year did World War II begin?", "a": ["1937","1938","1939","1940"], "correct": 2},
            {"q": "How many players are on a football team?", "a": ["9","10","11","12"], "correct": 2},
            {"q": "Which country is the largest by area?", "a": ["USA","China","Canada","Russia"], "correct": 3},
            {"q": "Who painted the Mona Lisa?", "a": ["Michelangelo","Raphael","Leonardo da Vinci","Botticelli"], "correct": 2},
            {"q": "What is the smallest country in the world?", "a": ["Monaco","Vatican","San Marino","Liechtenstein"], "correct": 1},
            {"q": "How many bones does an adult human have?", "a": ["186","206","226","246"], "correct": 1},
            {"q": "Which planet is closest to the Sun?", "a": ["Venus","Earth","Mercury","Mars"], "correct": 2},
            {"q": "In which city is the Colosseum located?", "a": ["Athens","Rome","Madrid","Paris"], "correct": 1},
            {"q": "Who was the first president of the USA?", "a": ["Abraham Lincoln","Thomas Jefferson","John Adams","George Washington"], "correct": 3},
            {"q": "What is the speed of light (approximately)?", "a": ["200,000 km/s","300,000 km/s","400,000 km/s","500,000 km/s"], "correct": 1},
            {"q": "How many chromosomes does a healthy human have?", "a": ["23","44","46","48"], "correct": 2},
            {"q": "What is the capital of Australia?", "a": ["Sydney","Melbourne","Brisbane","Canberra"], "correct": 3},
            {"q": "What is the chemical symbol for iron?", "a": ["Fe","Zn","Ir","In"], "correct": 0},
            {"q": "Which organ produces insulin?", "a": ["Liver","Kidneys","Pancreas","Spleen"], "correct": 2},
            {"q": "How many strings does a classical guitar have?", "a": ["4","5","6","7"], "correct": 2},
            {"q": "How many notes are in a musical scale?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "What is the deepest point in the ocean?", "a": ["Puerto Rico Trench","Mariana Trench","Tonga Trench","Philippine Trench"], "correct": 1},
            {"q": "Who wrote 'Crime and Punishment'?", "a": ["Leo Tolstoy","Anton Chekhov","Ivan Turgenev","Fyodor Dostoevsky"], "correct": 3},
        ],
        "hard": [
            {"q": "Which element has atomic number 79?", "a": ["Silver","Platinum","Gold","Copper"], "correct": 2},
            {"q": "Who developed the theory of relativity?", "a": ["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"], "correct": 2},
            {"q": "Who was the first astronaut to walk in open space?", "a": ["Yuri Gagarin","Alexei Leonov","German Titov","Valentina Tereshkova"], "correct": 1},
            {"q": "Who proved Fermat's Last Theorem?", "a": ["Carl Gauss","Andrew Wiles","Henri Poincaré","Leonhard Euler"], "correct": 1},
            {"q": "How many quantum numbers describe an electron?", "a": ["2","3","4","5"], "correct": 2},
            {"q": "In what year did the French Revolution begin?", "a": ["1776","1783","1789","1799"], "correct": 2},
            {"q": "What is the smallest bone in the human body?", "a": ["Phalanx","Stapes","Clavicle","Carpal"], "correct": 1},
            {"q": "Who discovered penicillin?", "a": ["Louis Pasteur","Robert Koch","Alexander Fleming","Joseph Lister"], "correct": 2},
            {"q": "What is the chemical symbol for gold?", "a": ["Ag","Pt","Au","Cu"], "correct": 2},
            {"q": "How many symphonies did Beethoven write?", "a": ["7","8","9","10"], "correct": 2},
            {"q": "What is the distance from Earth to the Moon (approximately)?", "a": ["184,000 km","284,000 km","384,000 km","484,000 km"], "correct": 2},
            {"q": "Who authored the Iliad and the Odyssey?", "a": ["Virgil","Hesiod","Homer","Aesop"], "correct": 2},
            {"q": "What is the formula for sulfuric acid?", "a": ["HCl","HNO3","H2SO4","H3PO4"], "correct": 2},
            {"q": "What is the highest point in Africa?", "a": ["Mount Kenya","Kilimanjaro","Ras Dashen","Mount Meru"], "correct": 1},
            {"q": "Who wrote 'Faust'?", "a": ["Schiller","Heine","Goethe","Kafka"], "correct": 2},
            {"q": "Which is the deepest lake in the world?", "a": ["Caspian Sea","Baikal","Tanganyika","Superior"], "correct": 1},
            {"q": "Who developed the theory of evolution?", "a": ["Gregor Mendel","Jean-Baptiste Lamarck","Charles Darwin","Thomas Huxley"], "correct": 2},
            {"q": "How many elements are in the periodic table?", "a": ["112","116","118","120"], "correct": 2},
            {"q": "Who developed the first smallpox vaccine?", "a": ["Louis Pasteur","Edward Jenner","Robert Koch","Ilya Mechnikov"], "correct": 1},
            {"q": "What is the coldest temperature ever recorded on Earth?", "a": ["-79°C","-89°C","-99°C","-109°C"], "correct": 1},
            {"q": "Which part of the brain controls balance?", "a": ["Cortex","Cerebellum","Hippocampus","Thalamus"], "correct": 1},
            {"q": "In which century did Leonardo da Vinci live?", "a": ["14th","15th","16th","17th"], "correct": 1},
            {"q": "Who wrote 'The Divine Comedy'?", "a": ["Petrarch","Boccaccio","Dante Alighieri","Ariosto"], "correct": 2},
            {"q": "How many bits are in one byte?", "a": ["4","6","8","16"], "correct": 2},
            {"q": "Who wrote Symphony No. 9 with 'Ode to Joy'?", "a": ["Mozart","Schubert","Beethoven","Haydn"], "correct": 2},
            {"q": "Which country has the most lakes?", "a": ["Finland","Russia","Canada","USA"], "correct": 2},
            {"q": "Who painted 'The Starry Night'?", "a": ["Paul Gauguin","Claude Monet","Vincent van Gogh","Paul Cézanne"], "correct": 2},
            {"q": "What is the largest gland in the human body?", "a": ["Pancreas","Thyroid","Liver","Spleen"], "correct": 2},
            {"q": "Which city hosted the 1936 Olympic Games?", "a": ["London","Paris","Berlin","Rome"], "correct": 2},
            {"q": "What law describes the relationship between gas pressure and volume?", "a": ["Charles's Law","Gay-Lussac's Law","Boyle's Law","Avogadro's Law"], "correct": 2},
        ],
    },

    # ── FRANÇAIS ─────────────────────────────────────────────
    "fr": {
        "easy": [
            {"q": "Quelle est la capitale de la France?", "a": ["Lyon","Marseille","Paris","Bordeaux"], "correct": 2},
            {"q": "Combien de jours y a-t-il dans une semaine?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Quelle est la plus grande planète?", "a": ["Terre","Mars","Jupiter","Saturne"], "correct": 2},
            {"q": "Combien de couleurs y a-t-il dans un arc-en-ciel?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Quel est le plus grand océan?", "a": ["Atlantique","Indien","Arctique","Pacifique"], "correct": 3},
            {"q": "Combien de mois y a-t-il dans une année?", "a": ["10","11","12","13"], "correct": 2},
            {"q": "Quelle est la plus haute montagne du monde?", "a": ["K2","Kangchenjunga","Everest","Makalu"], "correct": 2},
            {"q": "Quelle est la capitale de l'Allemagne?", "a": ["Munich","Hambourg","Berlin","Francfort"], "correct": 2},
            {"q": "Combien d'heures y a-t-il dans une journée?", "a": ["12","20","24","48"], "correct": 2},
            {"q": "Quel est le plus grand animal sur Terre?", "a": ["Éléphant","Baleine bleue","Requin","Girafe"], "correct": 1},
        ],
        "medium": [
            {"q": "Quel est le plus long fleuve du monde?", "a": ["Amazone","Nil","Yangtsé","Mississippi"], "correct": 1},
            {"q": "Quelle est la formule chimique de l'eau?", "a": ["CO2","H2O","O2","NaCl"], "correct": 1},
            {"q": "En quelle année la Seconde Guerre mondiale a-t-elle commencé?", "a": ["1937","1938","1939","1940"], "correct": 2},
            {"q": "Combien de joueurs y a-t-il dans une équipe de football?", "a": ["9","10","11","12"], "correct": 2},
            {"q": "Quel est le plus grand pays par superficie?", "a": ["États-Unis","Chine","Canada","Russie"], "correct": 3},
            {"q": "Qui a peint la Joconde?", "a": ["Michel-Ange","Raphaël","Léonard de Vinci","Botticelli"], "correct": 2},
            {"q": "Quel est le plus petit pays du monde?", "a": ["Monaco","Vatican","Saint-Marin","Liechtenstein"], "correct": 1},
            {"q": "Combien d'os a un adulte?", "a": ["186","206","226","246"], "correct": 1},
            {"q": "Quelle planète est la plus proche du Soleil?", "a": ["Vénus","Terre","Mercure","Mars"], "correct": 2},
            {"q": "Dans quelle ville se trouve le Colisée?", "a": ["Athènes","Rome","Madrid","Paris"], "correct": 1},
            {"q": "Qui était le premier président des États-Unis?", "a": ["Abraham Lincoln","Thomas Jefferson","John Adams","George Washington"], "correct": 3},
            {"q": "Quelle est la vitesse de la lumière?", "a": ["200 000 km/s","300 000 km/s","400 000 km/s","500 000 km/s"], "correct": 1},
            {"q": "Combien de chromosomes a un être humain?", "a": ["23","44","46","48"], "correct": 2},
            {"q": "Quelle est la capitale de l'Australie?", "a": ["Sydney","Melbourne","Brisbane","Canberra"], "correct": 3},
            {"q": "Quel est le symbole chimique du fer?", "a": ["Fe","Zn","Ir","In"], "correct": 0},
            {"q": "Quel organe produit l'insuline?", "a": ["Foie","Reins","Pancréas","Rate"], "correct": 2},
            {"q": "Combien de cordes a une guitare classique?", "a": ["4","5","6","7"], "correct": 2},
            {"q": "Combien de notes y a-t-il dans une gamme musicale?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Quel est le point le plus profond de l'océan?", "a": ["Fosse de Porto Rico","Fosse des Mariannes","Fosse des Tonga","Fosse des Philippines"], "correct": 1},
            {"q": "Qui a écrit 'Crime et Châtiment'?", "a": ["Léon Tolstoï","Anton Tchekhov","Ivan Tourgueniev","Fiodor Dostoïevski"], "correct": 3},
        ],
        "hard": [
            {"q": "Quel élément a le numéro atomique 79?", "a": ["Argent","Platine","Or","Cuivre"], "correct": 2},
            {"q": "Qui a développé la théorie de la relativité?", "a": ["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"], "correct": 2},
            {"q": "Qui a été le premier cosmonaute à marcher dans l'espace?", "a": ["Youri Gagarine","Alexeï Leonov","Guerman Titov","Valentina Terechkova"], "correct": 1},
            {"q": "Qui a prouvé le dernier théorème de Fermat?", "a": ["Carl Gauss","Andrew Wiles","Henri Poincaré","Leonhard Euler"], "correct": 1},
            {"q": "Combien de nombres quantiques décrivent un électron?", "a": ["2","3","4","5"], "correct": 2},
            {"q": "En quelle année a eu lieu la Révolution française?", "a": ["1776","1783","1789","1799"], "correct": 2},
            {"q": "Quel est le plus petit os du corps humain?", "a": ["Phalange","Étrier","Clavicule","Carpien"], "correct": 1},
            {"q": "Qui a découvert la pénicilline?", "a": ["Louis Pasteur","Robert Koch","Alexander Fleming","Joseph Lister"], "correct": 2},
            {"q": "Quel est le symbole chimique de l'or?", "a": ["Ag","Pt","Au","Cu"], "correct": 2},
            {"q": "Combien de symphonies Beethoven a-t-il écrites?", "a": ["7","8","9","10"], "correct": 2},
            {"q": "Quelle est la distance entre la Terre et la Lune?", "a": ["184 000 km","284 000 km","384 000 km","484 000 км"], "correct": 2},
            {"q": "Qui est l'auteur de l'Iliade et de l'Odyssée?", "a": ["Virgile","Hésiode","Homère","Ésope"], "correct": 2},
            {"q": "Quelle est la formule de l'acide sulfurique?", "a": ["HCl","HNO3","H2SO4","H3PO4"], "correct": 2},
            {"q": "Quel est le point culminant de l'Afrique?", "a": ["Mont Kenya","Kilimandjaro","Ras Dashen","Mont Meru"], "correct": 1},
            {"q": "Qui a écrit 'Faust'?", "a": ["Schiller","Heine","Goethe","Kafka"], "correct": 2},
            {"q": "Quel est le lac le plus profond du monde?", "a": ["Mer Caspienne","Baïkal","Tanganyika","Supérieur"], "correct": 1},
            {"q": "Qui a développé la théorie de l'évolution?", "a": ["Gregor Mendel","Jean-Baptiste Lamarck","Charles Darwin","Thomas Huxley"], "correct": 2},
            {"q": "Combien d'éléments y a-t-il dans le tableau périodique?", "a": ["112","116","118","120"], "correct": 2},
            {"q": "Qui a développé le premier vaccin contre la variole?", "a": ["Louis Pasteur","Edward Jenner","Robert Koch","Ilya Mechnikov"], "correct": 1},
            {"q": "Quelle est la température la plus froide jamais enregistrée?", "a": ["-79°C","-89°C","-99°C","-109°C"], "correct": 1},
            {"q": "Quelle partie du cerveau contrôle l'équilibre?", "a": ["Cortex","Cervelet","Hippocampe","Thalamus"], "correct": 1},
            {"q": "Dans quel siècle Léonard de Vinci a-t-il vécu?", "a": ["XIVe","XVe","XVIe","XVIIe"], "correct": 1},
            {"q": "Qui a écrit 'La Divine Comédie'?", "a": ["Pétrarque","Boccace","Dante Alighieri","Arioste"], "correct": 2},
            {"q": "Combien de bits y a-t-il dans un octet?", "a": ["4","6","8","16"], "correct": 2},
            {"q": "Qui a écrit la Symphonie n°9 avec l'Ode à la joie?", "a": ["Mozart","Schubert","Beethoven","Haydn"], "correct": 2},
            {"q": "Quel pays a le plus de lacs au monde?", "a": ["Finlande","Russie","Canada","États-Unis"], "correct": 2},
            {"q": "Qui a peint 'La Nuit étoilée'?", "a": ["Paul Gauguin","Claude Monet","Vincent van Gogh","Paul Cézanne"], "correct": 2},
            {"q": "Quelle est la plus grande glande du corps humain?", "a": ["Pancréas","Thyroïde","Foie","Rate"], "correct": 2},
            {"q": "Dans quelle ville se sont déroulés les JO de 1936?", "a": ["Londres","Paris","Berlin","Rome"], "correct": 2},
            {"q": "Quelle loi décrit la relation entre pression et volume d'un gaz?", "a": ["Loi de Charles","Loi de Gay-Lussac","Loi de Boyle-Mariotte","Loi d'Avogadro"], "correct": 2},
        ],
    },

    # ── DEUTSCH ──────────────────────────────────────────────
    "de": {
        "easy": [
            {"q": "Was ist die Hauptstadt von Deutschland?", "a": ["München","Hamburg","Berlin","Frankfurt"], "correct": 2},
            {"q": "Wie viele Tage hat eine Woche?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Welcher ist der größte Planet?", "a": ["Erde","Mars","Jupiter","Saturn"], "correct": 2},
            {"q": "Wie viele Farben hat ein Regenbogen?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Welcher Ozean ist der größte?", "a": ["Atlantischer","Indischer","Arktischer","Pazifischer"], "correct": 3},
            {"q": "Wie viele Monate hat ein Jahr?", "a": ["10","11","12","13"], "correct": 2},
            {"q": "Was ist der höchste Berg der Welt?", "a": ["K2","Kangchendzönga","Everest","Makalu"], "correct": 2},
            {"q": "Was ist die Hauptstadt von Frankreich?", "a": ["Berlin","Madrid","Rom","Paris"], "correct": 3},
            {"q": "Wie viele Stunden hat ein Tag?", "a": ["12","20","24","48"], "correct": 2},
            {"q": "Was ist das größte Tier der Erde?", "a": ["Elefant","Blauwal","Hai","Giraffe"], "correct": 1},
        ],
        "medium": [
            {"q": "Was ist der längste Fluss der Welt?", "a": ["Amazonas","Nil","Jangtse","Mississippi"], "correct": 1},
            {"q": "Was ist die chemische Formel für Wasser?", "a": ["CO2","H2O","O2","NaCl"], "correct": 1},
            {"q": "In welchem Jahr begann der Zweite Weltkrieg?", "a": ["1937","1938","1939","1940"], "correct": 2},
            {"q": "Wie viele Spieler hat eine Fußballmannschaft?", "a": ["9","10","11","12"], "correct": 2},
            {"q": "Welches Land ist das größte nach Fläche?", "a": ["USA","China","Kanada","Russland"], "correct": 3},
            {"q": "Wer malte die Mona Lisa?", "a": ["Michelangelo","Raffael","Leonardo da Vinci","Botticelli"], "correct": 2},
            {"q": "Was ist das kleinste Land der Welt?", "a": ["Monaco","Vatikan","San Marino","Liechtenstein"], "correct": 1},
            {"q": "Wie viele Knochen hat ein erwachsener Mensch?", "a": ["186","206","226","246"], "correct": 1},
            {"q": "Welcher Planet ist der Sonne am nächsten?", "a": ["Venus","Erde","Merkur","Mars"], "correct": 2},
            {"q": "In welcher Stadt steht das Kolosseum?", "a": ["Athen","Rom","Madrid","Paris"], "correct": 1},
            {"q": "Wer war der erste Präsident der USA?", "a": ["Abraham Lincoln","Thomas Jefferson","John Adams","George Washington"], "correct": 3},
            {"q": "Wie schnell ist das Licht (ungefähr)?", "a": ["200 000 km/s","300 000 km/s","400 000 km/s","500 000 km/s"], "correct": 1},
            {"q": "Wie viele Chromosomen hat ein gesunder Mensch?", "a": ["23","44","46","48"], "correct": 2},
            {"q": "Was ist die Hauptstadt von Australien?", "a": ["Sydney","Melbourne","Brisbane","Canberra"], "correct": 3},
            {"q": "Was ist das chemische Symbol für Eisen?", "a": ["Fe","Zn","Ir","In"], "correct": 0},
            {"q": "Welches Organ produziert Insulin?", "a": ["Leber","Nieren","Bauchspeicheldrüse","Milz"], "correct": 2},
            {"q": "Wie viele Saiten hat eine klassische Gitarre?", "a": ["4","5","6","7"], "correct": 2},
            {"q": "Wie viele Noten hat eine Tonleiter?", "a": ["5","6","7","8"], "correct": 2},
            {"q": "Was ist der tiefste Punkt des Ozeans?", "a": ["Puerto-Rico-Graben","Marianengraben","Tongagraben","Philippinengraben"], "correct": 1},
            {"q": "Wer schrieb 'Schuld und Sühne'?", "a": ["Leo Tolstoi","Anton Tschechow","Iwan Turgenjew","Fjodor Dostojewski"], "correct": 3},
        ],
        "hard": [
            {"q": "Welches Element hat die Ordnungszahl 79?", "a": ["Silber","Platin","Gold","Kupfer"], "correct": 2},
            {"q": "Wer entwickelte die Relativitätstheorie?", "a": ["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"], "correct": 2},
            {"q": "Wer war der erste Kosmonaut im offenen Weltraum?", "a": ["Juri Gagarin","Alexei Leonow","German Titow","Valentina Tereschkowa"], "correct": 1},
            {"q": "Wer bewies den letzten Satz von Fermat?", "a": ["Carl Gauß","Andrew Wiles","Henri Poincaré","Leonhard Euler"], "correct": 1},
            {"q": "Wie viele Quantenzahlen beschreiben ein Elektron?", "a": ["2","3","4","5"], "correct": 2},
            {"q": "In welchem Jahr begann die Französische Revolution?", "a": ["1776","1783","1789","1799"], "correct": 2},
            {"q": "Was ist der kleinste Knochen im menschlichen Körper?", "a": ["Phalanx","Steigbügel","Schlüsselbein","Handwurzelknochen"], "correct": 1},
            {"q": "Wer entdeckte das Penicillin?", "a": ["Louis Pasteur","Robert Koch","Alexander Fleming","Joseph Lister"], "correct": 2},
            {"q": "Was ist das chemische Symbol für Gold?", "a": ["Ag","Pt","Au","Cu"], "correct": 2},
            {"q": "Wie viele Sinfonien schrieb Beethoven?", "a": ["7","8","9","10"], "correct": 2},
            {"q": "Wie weit ist der Mond von der Erde entfernt?", "a": ["184 000 km","284 000 km","384 000 km","484 000 km"], "correct": 2},
            {"q": "Wer ist der Autor der Ilias und der Odyssee?", "a": ["Vergil","Hesiod","Homer","Äsop"], "correct": 2},
            {"q": "Was ist die Formel für Schwefelsäure?", "a": ["HCl","HNO3","H2SO4","H3PO4"], "correct": 2},
            {"q": "Was ist der höchste Punkt Afrikas?", "a": ["Mount Kenya","Kilimandscharo","Ras Dashen","Mount Meru"], "correct": 1},
            {"q": "Wer schrieb 'Faust'?", "a": ["Schiller","Heine","Goethe","Kafka"], "correct": 2},
            {"q": "Was ist der tiefste See der Welt?", "a": ["Kaspisches Meer","Baikalsee","Tanganjikasee","Oberer See"], "correct": 1},
            {"q": "Wer entwickelte die Evolutionstheorie?", "a": ["Gregor Mendel","Jean-Baptiste Lamarck","Charles Darwin","Thomas Huxley"], "correct": 2},
            {"q": "Wie viele Elemente gibt es im Periodensystem?", "a": ["112","116","118","120"], "correct": 2},
            {"q": "Wer entwickelte den ersten Pockenimpfstoff?", "a": ["Louis Pasteur","Edward Jenner","Robert Koch","Ilja Metschnikow"], "correct": 1},
            {"q": "Was ist die kälteste je auf der Erde gemessene Temperatur?", "a": ["-79°C","-89°C","-99°C","-109°C"], "correct": 1},
            {"q": "Welcher Teil des Gehirns steuert das Gleichgewicht?", "a": ["Kortex","Kleinhirn","Hippocampus","Thalamus"], "correct": 1},
            {"q": "In welchem Jahrhundert lebte Leonardo da Vinci?", "a": ["14.","15.","16.","17."], "correct": 1},
            {"q": "Wer schrieb 'Die Göttliche Komödie'?", "a": ["Petrarca","Boccaccio","Dante Alighieri","Ariost"], "correct": 2},
            {"q": "Wie viele Bits sind in einem Byte?", "a": ["4","6","8","16"], "correct": 2},
            {"q": "Wer schrieb die 9. Sinfonie mit der 'Ode an die Freude'?", "a": ["Mozart","Schubert","Beethoven","Haydn"], "correct": 2},
            {"q": "Welches Land hat die meisten Seen?", "a": ["Finnland","Russland","Kanada","USA"], "correct": 2},
            {"q": "Wer malte 'Sternennacht'?", "a": ["Paul Gauguin","Claude Monet","Vincent van Gogh","Paul Cézanne"], "correct": 2},
            {"q": "Was ist die größte Drüse im menschlichen Körper?", "a": ["Bauchspeicheldrüse","Schilddrüse","Leber","Milz"], "correct": 2},
            {"q": "In welcher Stadt fanden die Olympischen Spiele 1936 statt?", "a": ["London","Paris","Berlin","Rom"], "correct": 2},
            {"q": "Welches Gesetz beschreibt den Zusammenhang zwischen Druck und Volumen?", "a": ["Gesetz von Charles","Gesetz von Gay-Lussac","Gesetz von Boyle-Mariotte","Gesetz von Avogadro"], "correct": 2},
        ],
    },
}

# ═══════════════════════════════════════════════════════════════
#  НЕСКІНЧЕННИЙ РЕЖИМ — 100 питань (тільки для infinite)
# ═══════════════════════════════════════════════════════════════
INFINITE_QUESTIONS = {
    "uk": [
        # 30 легких
        {"q": "Яка столиця України?", "a": ["Львів","Київ","Харків","Одеса"], "correct": 1, "diff": "easy"},
        {"q": "Скільки днів у тижні?", "a": ["5","6","7","8"], "correct": 2, "diff": "easy"},
        {"q": "Яка найбільша планета Сонячної системи?", "a": ["Земля","Марс","Юпітер","Сатурн"], "correct": 2, "diff": "easy"},
        {"q": "Скільки кольорів у веселці?", "a": ["5","6","7","8"], "correct": 2, "diff": "easy"},
        {"q": "Який океан найбільший?", "a": ["Атлантичний","Індійський","Арктичний","Тихий"], "correct": 3, "diff": "easy"},
        {"q": "Скільки місяців у році?", "a": ["10","11","12","13"], "correct": 2, "diff": "easy"},
        {"q": "Яка тварина є символом Австралії?", "a": ["Коала","Кенгуру","Динго","Вомбат"], "correct": 1, "diff": "easy"},
        {"q": "Скільки сторін у трикутника?", "a": ["2","3","4","5"], "correct": 1, "diff": "easy"},
        {"q": "Яка найвища гора у світі?", "a": ["К2","Канченджанга","Еверест","Макалу"], "correct": 2, "diff": "easy"},
        {"q": "Яка столиця Франції?", "a": ["Берлін","Мадрид","Рим","Париж"], "correct": 3, "diff": "easy"},
        {"q": "Скільки годин у добі?", "a": ["12","20","24","48"], "correct": 2, "diff": "easy"},
        {"q": "Яка найбільша тварина на Землі?", "a": ["Слон","Синій кит","Акула","Жираф"], "correct": 1, "diff": "easy"},
        {"q": "Яким кольором є листя більшості рослин?", "a": ["Жовтим","Червоним","Зеленим","Синім"], "correct": 2, "diff": "easy"},
        {"q": "Скільки сторін у квадрата?", "a": ["3","4","5","6"], "correct": 1, "diff": "easy"},
        {"q": "Яка столиця Німеччини?", "a": ["Мюнхен","Гамбург","Берлін","Франкфурт"], "correct": 2, "diff": "easy"},
        {"q": "Хто написав 'Кобзар'?", "a": ["Іван Франко","Леся Українка","Тарас Шевченко","Коцюбинський"], "correct": 2, "diff": "easy"},
        {"q": "Скільки хвилин в одній годині?", "a": ["30","45","60","90"], "correct": 2, "diff": "easy"},
        {"q": "Яка найшвидша тварина на суші?", "a": ["Лев","Гепард","Страус","Антилопа"], "correct": 1, "diff": "easy"},
        {"q": "Яка столиця Великобританії?", "a": ["Единбург","Манчестер","Лондон","Бірмінгем"], "correct": 2, "diff": "easy"},
        {"q": "Скільки очей у павука?", "a": ["2","4","6","8"], "correct": 3, "diff": "easy"},
        {"q": "Яка найбільша пустеля у світі?", "a": ["Гобі","Сахара","Антарктида","Аравійська"], "correct": 2, "diff": "easy"},
        {"q": "Який газ ми вдихаємо?", "a": ["Вуглекислий","Водень","Кисень","Азот"], "correct": 2, "diff": "easy"},
        {"q": "Скільки нот у музичній гамі?", "a": ["5","6","7","8"], "correct": 2, "diff": "easy"},
        {"q": "Яка столиця Японії?", "a": ["Осака","Кіото","Токіо","Хіросіма"], "correct": 2, "diff": "easy"},
        {"q": "Скільки континентів на Землі?", "a": ["5","6","7","8"], "correct": 2, "diff": "easy"},
        {"q": "Яка найдовша річка в Україні?", "a": ["Дністер","Десна","Дніпро","Південний Буг"], "correct": 2, "diff": "easy"},
        {"q": "Скільки секунд у хвилині?", "a": ["30","45","60","100"], "correct": 2, "diff": "easy"},
        {"q": "Яка столиця Іспанії?", "a": ["Барселона","Мадрид","Севілья","Валенсія"], "correct": 1, "diff": "easy"},
        {"q": "Який орган перекачує кров?", "a": ["Легені","Печінка","Серце","Нирки"], "correct": 2, "diff": "easy"},
        {"q": "Скільки кутів у прямокутника?", "a": ["2","3","4","5"], "correct": 2, "diff": "easy"},
        # 40 середніх
        {"q": "Яка найдовша річка у світі?", "a": ["Амазонка","Ніл","Янцзи","Міссісіпі"], "correct": 1, "diff": "medium"},
        {"q": "Яка хімічна формула води?", "a": ["CO2","H2O","O2","NaCl"], "correct": 1, "diff": "medium"},
        {"q": "У якому році почалася Друга світова війна?", "a": ["1937","1938","1939","1940"], "correct": 2, "diff": "medium"},
        {"q": "Скільки гравців у футбольній команді на полі?", "a": ["9","10","11","12"], "correct": 2, "diff": "medium"},
        {"q": "Яка країна найбільша за площею?", "a": ["США","Китай","Канада","Росія"], "correct": 3, "diff": "medium"},
        {"q": "Який газ рослини поглинають під час фотосинтезу?", "a": ["Кисень","Азот","Вуглекислий газ","Водень"], "correct": 2, "diff": "medium"},
        {"q": "Скільки струн у класичній гітарі?", "a": ["4","5","6","7"], "correct": 2, "diff": "medium"},
        {"q": "Хто намалював 'Мона Ліза'?", "a": ["Мікеланджело","Рафаель","Леонардо да Вінчі","Боттічеллі"], "correct": 2, "diff": "medium"},
        {"q": "Яка найменша країна у світі?", "a": ["Монако","Ватикан","Сан-Марино","Ліхтенштейн"], "correct": 1, "diff": "medium"},
        {"q": "Скільки кісток у дорослої людини?", "a": ["186","206","226","246"], "correct": 1, "diff": "medium"},
        {"q": "Яка планета найближча до Сонця?", "a": ["Венера","Земля","Меркурій","Марс"], "correct": 2, "diff": "medium"},
        {"q": "У якому місті знаходиться Колізей?", "a": ["Афіни","Рим","Мадрид","Париж"], "correct": 1, "diff": "medium"},
        {"q": "Хто був першим президентом США?", "a": ["Авраам Лінкольн","Томас Джефферсон","Джон Адамс","Джордж Вашингтон"], "correct": 3, "diff": "medium"},
        {"q": "Яка швидкість світла (приблизно)?", "a": ["200 000 км/с","300 000 км/с","400 000 км/с","500 000 км/с"], "correct": 1, "diff": "medium"},
        {"q": "Скільки хромосом у клітині здорової людини?", "a": ["23","44","46","48"], "correct": 2, "diff": "medium"},
        {"q": "Яка столиця Австралії?", "a": ["Сідней","Мельбурн","Брісбен","Канберра"], "correct": 3, "diff": "medium"},
        {"q": "Який хімічний символ заліза?", "a": ["Fe","Zn","Ir","In"], "correct": 0, "diff": "medium"},
        {"q": "Яка найменша кістка в тілі людини?", "a": ["Фаланга","Стремінце","Ключиця","Зап'ястна"], "correct": 1, "diff": "medium"},
        {"q": "Який орган виробляє інсулін?", "a": ["Печінка","Нирки","Підшлункова залоза","Селезінка"], "correct": 2, "diff": "medium"},
        {"q": "Яка найбільша залоза в тілі людини?", "a": ["Підшлункова","Щитоподібна","Печінка","Селезінка"], "correct": 2, "diff": "medium"},
        {"q": "У якому році Україна проголосила незалежність?", "a": ["1989","1990","1991","1992"], "correct": 2, "diff": "medium"},
        {"q": "Яка частота електричного струму в Україні?", "a": ["50 Гц","60 Гц","40 Гц","55 Гц"], "correct": 0, "diff": "medium"},
        {"q": "Скільки букв в українському алфавіті?", "a": ["30","32","33","36"], "correct": 1, "diff": "medium"},
        {"q": "Яка країна має найбільшу кількість населення?", "a": ["Індія","США","Китай","Індонезія"], "correct": 0, "diff": "medium"},
        {"q": "Хто написав 'Злочин і кара'?", "a": ["Лев Толстой","Антон Чехов","Іван Тургенєв","Федір Достоєвський"], "correct": 3, "diff": "medium"},
        {"q": "Яка температура кипіння води?", "a": ["90°C","95°C","100°C","105°C"], "correct": 2, "diff": "medium"},
        {"q": "Яка найглибша точка океану?", "a": ["Жолоб Пуерто-Ріко","Маріанська западина","Жолоб Тонга","Жолоб Філіппін"], "correct": 1, "diff": "medium"},
        {"q": "Скільки планет у Сонячній системі?", "a": ["7","8","9","10"], "correct": 1, "diff": "medium"},
        {"q": "Яка довжина екватора Землі (приблизно)?", "a": ["36 000 км","40 075 км","45 000 км","38 500 км"], "correct": 1, "diff": "medium"},
        {"q": "Хто є автором картини 'Зоряна ніч'?", "a": ["Поль Гоген","Клод Моне","Вінсент ван Гог","Поль Сезанн"], "correct": 2, "diff": "medium"},
        {"q": "Яка швидкість звуку в повітрі при 20°C?", "a": ["243 м/с","343 м/с","443 м/с","543 м/с"], "correct": 1, "diff": "medium"},
        {"q": "У якому місті відбулися Олімпійські ігри 1936 року?", "a": ["Лондон","Париж","Берлін","Рим"], "correct": 2, "diff": "medium"},
        {"q": "Який рік вважається роком заснування Києва?", "a": ["482","582","682","782"], "correct": 0, "diff": "medium"},
        {"q": "Хто написав симфонію №9 з 'Одою до радості'?", "a": ["Моцарт","Шуберт","Бетховен","Гайдн"], "correct": 2, "diff": "medium"},
        {"q": "Яка столиця Канади?", "a": ["Торонто","Монреаль","Ванкувер","Оттава"], "correct": 3, "diff": "medium"},
        {"q": "Яке місто є батьківщиною Олімпійських ігор?", "a": ["Афіни","Олімпія","Спарта","Коринф"], "correct": 1, "diff": "medium"},
        {"q": "Яка країна першою надала жінкам право голосу?", "a": ["Велика Британія","США","Нова Зеландія","Франція"], "correct": 2, "diff": "medium"},
        {"q": "Який елемент є найпоширенішим у земній корі?", "a": ["Залізо","Кремній","Кисень","Алюміній"], "correct": 2, "diff": "medium"},
        {"q": "Скільки держав входить до ЄС?", "a": ["24","25","27","30"], "correct": 2, "diff": "medium"},
        {"q": "Яка столиця Бразилії?", "a": ["Ріо-де-Жанейро","Сан-Паулу","Бразиліа","Сальвадор"], "correct": 2, "diff": "medium"},
        # 30 важких
        {"q": "Який елемент має атомний номер 79?", "a": ["Срібло","Платина","Золото","Мідь"], "correct": 2, "diff": "hard"},
        {"q": "Хто автор теорії відносності?", "a": ["Ісаак Ньютон","Нільс Бор","Альберт Ейнштейн","Макс Планк"], "correct": 2, "diff": "hard"},
        {"q": "Хто був першим космонавтом у відкритому космосі?", "a": ["Юрій Гагарін","Олексій Леонов","Герман Тітов","Валентина Терешкова"], "correct": 1, "diff": "hard"},
        {"q": "Який математик довів останню теорему Ферма?", "a": ["Карл Гаус","Ендрю Вайлс","Анрі Пуанкаре","Леонард Ейлер"], "correct": 1, "diff": "hard"},
        {"q": "Скільки квантових чисел описують стан електрона?", "a": ["2","3","4","5"], "correct": 2, "diff": "hard"},
        {"q": "У якому році відбулася Французька революція?", "a": ["1776","1783","1789","1799"], "correct": 2, "diff": "hard"},
        {"q": "Яка найменша кістка в тілі людини?", "a": ["Фаланга","Стремінце","Ключиця","Зап'ястна"], "correct": 1, "diff": "hard"},
        {"q": "Хто відкрив пеніцилін?", "a": ["Луї Пастер","Роберт Кох","Александр Флемінг","Джозеф Лістер"], "correct": 2, "diff": "hard"},
        {"q": "Який хімічний символ золота?", "a": ["Ag","Pt","Au","Cu"], "correct": 2, "diff": "hard"},
        {"q": "Скільки симфоній написав Бетховен?", "a": ["7","8","9","10"], "correct": 2, "diff": "hard"},
        {"q": "Яка відстань від Землі до Місяця (приблизно)?", "a": ["184 000 км","284 000 км","384 000 км","484 000 км"], "correct": 2, "diff": "hard"},
        {"q": "Хто є автором 'Іліади' та 'Одіссеї'?", "a": ["Вергілій","Гесіод","Гомер","Езоп"], "correct": 2, "diff": "hard"},
        {"q": "Яка формула сірчаної кислоти?", "a": ["HCl","HNO3","H2SO4","H3PO4"], "correct": 2, "diff": "hard"},
        {"q": "Яка найвища точка Африки?", "a": ["Гора Кенія","Кіліманджаро","Рас-Дашен","Монт-Мару"], "correct": 1, "diff": "hard"},
        {"q": "Хто написав 'Фауст'?", "a": ["Шиллер","Гейне","Гете","Кафка"], "correct": 2, "diff": "hard"},
        {"q": "Яке найглибше озеро у світі?", "a": ["Каспійське","Байкал","Танганьїка","Верхнє"], "correct": 1, "diff": "hard"},
        {"q": "Хто є автором теорії еволюції?", "a": ["Грегор Мендель","Жан-Батіст Ламарк","Чарльз Дарвін","Томас Хакслі"], "correct": 2, "diff": "hard"},
        {"q": "Скільки елементів у таблиці Менделєєва?", "a": ["112","116","118","120"], "correct": 2, "diff": "hard"},
        {"q": "Хто розробив першу вакцину проти віспи?", "a": ["Луї Пастер","Едвард Дженнер","Роберт Кох","Іван Мечников"], "correct": 1, "diff": "hard"},
        {"q": "Яка найхолодніша температура зафіксована на Землі?", "a": ["-79°C","-89°C","-99°C","-109°C"], "correct": 1, "diff": "hard"},
        {"q": "Яка частина мозку відповідає за рівновагу?", "a": ["Кора","Мозочок","Гіпокамп","Таламус"], "correct": 1, "diff": "hard"},
        {"q": "У якому столітті жив Леонардо да Вінчі?", "a": ["XIV","XV","XVI","XVII"], "correct": 1, "diff": "hard"},
        {"q": "Хто написав 'Божественну комедію'?", "a": ["Петрарка","Боккаччо","Данте Аліг'єрі","Аріосто"], "correct": 2, "diff": "hard"},
        {"q": "Яка кількість бітів у одному байті?", "a": ["4","6","8","16"], "correct": 2, "diff": "hard"},
        {"q": "Хто написав симфонію №9 з 'Одою до радості'?", "a": ["Моцарт","Шуберт","Бетховен","Гайдн"], "correct": 2, "diff": "hard"},
        {"q": "Яка країна має найбільше озер у світі?", "a": ["Фінляндія","Росія","Канада","США"], "correct": 2, "diff": "hard"},
        {"q": "Хто є автором картини 'Зоряна ніч'?", "a": ["Поль Гоген","Клод Моне","Вінсент ван Гог","Поль Сезанн"], "correct": 2, "diff": "hard"},
        {"q": "Яка найбільша залоза в тілі людини?", "a": ["Підшлункова","Щитоподібна","Печінка","Селезінка"], "correct": 2, "diff": "hard"},
        {"q": "Яке місто є батьківщиною Олімпійських ігор?", "a": ["Афіни","Олімпія","Спарта","Коринф"], "correct": 1, "diff": "hard"},
        {"q": "Який елемент є найпоширенішим у земній корі?", "a": ["Залізо","Кремній","Кисень","Алюміній"], "correct": 2, "diff": "hard"},
    ],

    # інші мови — placeholder (додай за потребою)
    "ru": [dict({"q": f"Бесконечный вопрос {i}?", "a": ["A","B","C","D"], "correct": (i-1)%4, "diff": ["easy","medium","hard"][i%3]}) for i in range(1,101)],
    "en": [dict({"q": f"Infinite question {i}?", "a": ["A","B","C","D"], "correct": (i-1)%4, "diff": ["easy","medium","hard"][i%3]}) for i in range(1,101)],
    "fr": [dict({"q": f"Question infinie {i}?", "a": ["A","B","C","D"], "correct": (i-1)%4, "diff": ["easy","medium","hard"][i%3]}) for i in range(1,101)],
    "de": [dict({"q": f"Unendliche Frage {i}?", "a": ["A","B","C","D"], "correct": (i-1)%4, "diff": ["easy","medium","hard"][i%3]}) for i in range(1,101)],
}


def get_questions(lang: str, difficulty: str) -> list:
    lang_q = QUESTIONS.get(lang, QUESTIONS["ru"])
    return list(lang_q.get(difficulty, []))


def get_infinite_questions(lang: str) -> list:
    return list(INFINITE_QUESTIONS.get(lang, INFINITE_QUESTIONS["ru"]))
