# ============================================================
#  ПЕРЕВОДЫ — 5 языков
# ============================================================

LANGUAGES = {
    "uk": "🇺🇦 Українська",
    "ru": "🇷🇺 Русский",
    "en": "🇬🇧 English",
    "fr": "🇫🇷 Français",
    "de": "🇩🇪 Deutsch",
}

TRANSLATIONS = {

    # ── Украинский ───────────────────────────────────────────
    "uk": {
        "title_top":        "ХТО ХОЧЕ СТАТИ",
        "title_main":       "МІЛЬЙОНЕРОМ?",
        "balance":          "Ваш баланс",
        "btn_start":        "▶   ПОЧАТИ",
        "btn_authors":      "✦   АВТОРИ",
        "btn_quit":         "✕   ВИЙТИ",
        "btn_language":     "🌐  МОВА",
        "difficulty_title": "ВИБІР СКЛАДНОСТІ",
        "btn_back":         "◀  НАЗАД",
        "btn_play":         "ГРАТИ →",
        "locked":           "🔒 Потрібно",
        "questions_lbl":    "пит.",
        "mixed":            "змішані питання",
        "hearts_lbl":       "❤ ×",
        "question_of":      "Питання {} з {}",
        "btn_exit_save":    "💰  ВИЙТИ І ЗБЕРЕГТИ",
        "wrong_lives":      "Невірно! Життів: {}",
        "game_over":        "GAME OVER",
        "lost_text":        "Ви втратили {}",
        "btn_restart":      "ПОЧАТИ ЗНОВУ",
        "btn_exit":         "ВИЙТИ",
        "victory_title":    "🏆  ВІТАЄМО!",
        "session_earned":   "Ви заробили за сесію: {}",
        "total_balance":    "Ваш загальний баланс: {}",
        "btn_play_more":    "▶  ГРАТИ ЩЕ",
        "btn_main_menu":    "◀  ГОЛОВНЕ МЕНЮ",
        "authors_title":    "✦  АВТОРИ  ✦",
        "diff_easy":        "Легкий",
        "diff_medium":      "Середній",
        "diff_hard":        "Важкий",
        "diff_infinite":    "♾  Нескінченний",
        "choose_language":  "ВИБІР МОВИ",
    },

    # ── Русский ──────────────────────────────────────────────
    "ru": {
        "title_top":        "КТО ХОЧЕТ СТАТЬ",
        "title_main":       "МИЛЛИОНЕРОМ?",
        "balance":          "Ваш баланс",
        "btn_start":        "▶   НАЧАТЬ",
        "btn_authors":      "✦   АВТОРЫ",
        "btn_quit":         "✕   ВЫЙТИ",
        "btn_language":     "🌐  ЯЗЫК",
        "difficulty_title": "ВЫБОР СЛОЖНОСТИ",
        "btn_back":         "◀  НАЗАД",
        "btn_play":         "ИГРАТЬ →",
        "locked":           "🔒 Требуется",
        "questions_lbl":    "вопр.",
        "mixed":            "смешанные вопросы",
        "hearts_lbl":       "❤ ×",
        "question_of":      "Вопрос {} из {}",
        "btn_exit_save":    "💰  ВЫЙТИ И СОХРАНИТЬ",
        "wrong_lives":      "Неверно! Жизней: {}",
        "game_over":        "GAME OVER",
        "lost_text":        "Вы потеряли {}",
        "btn_restart":      "НАЧАТЬ ЗАНОВО",
        "btn_exit":         "ВЫЙТИ",
        "victory_title":    "🏆  ПОЗДРАВЛЯЕМ!",
        "session_earned":   "Вы заработали за сессию: {}",
        "total_balance":    "Ваш общий баланс: {}",
        "btn_play_more":    "▶  ИГРАТЬ ЕЩЁ",
        "btn_main_menu":    "◀  ГЛАВНОЕ МЕНЮ",
        "authors_title":    "✦  АВТОРЫ  ✦",
        "diff_easy":        "Лёгкий",
        "diff_medium":      "Средний",
        "diff_hard":        "Тяжёлый",
        "diff_infinite":    "♾  Бесконечный",
        "choose_language":  "ВЫБОР ЯЗЫКА",
    },

    # ── English ──────────────────────────────────────────────
    "en": {
        "title_top":        "WHO WANTS TO BE A",
        "title_main":       "MILLIONAIRE?",
        "balance":          "Your balance",
        "btn_start":        "▶   START",
        "btn_authors":      "✦   AUTHORS",
        "btn_quit":         "✕   QUIT",
        "btn_language":     "🌐  LANGUAGE",
        "difficulty_title": "SELECT DIFFICULTY",
        "btn_back":         "◀  BACK",
        "btn_play":         "PLAY →",
        "locked":           "🔒 Requires",
        "questions_lbl":    "quest.",
        "mixed":            "mixed questions",
        "hearts_lbl":       "❤ ×",
        "question_of":      "Question {} of {}",
        "btn_exit_save":    "💰  EXIT & SAVE",
        "wrong_lives":      "Wrong! Lives left: {}",
        "game_over":        "GAME OVER",
        "lost_text":        "You lost {}",
        "btn_restart":      "PLAY AGAIN",
        "btn_exit":         "QUIT",
        "victory_title":    "🏆  CONGRATULATIONS!",
        "session_earned":   "You earned this session: {}",
        "total_balance":    "Your total balance: {}",
        "btn_play_more":    "▶  PLAY MORE",
        "btn_main_menu":    "◀  MAIN MENU",
        "authors_title":    "✦  AUTHORS  ✦",
        "diff_easy":        "Easy",
        "diff_medium":      "Medium",
        "diff_hard":        "Hard",
        "diff_infinite":    "♾  Infinite",
        "choose_language":  "CHOOSE LANGUAGE",
    },

    # ── Français ─────────────────────────────────────────────
    "fr": {
        "title_top":        "QUI VEUT GAGNER",
        "title_main":       "DES MILLIONS?",
        "balance":          "Votre solde",
        "btn_start":        "▶   COMMENCER",
        "btn_authors":      "✦   AUTEURS",
        "btn_quit":         "✕   QUITTER",
        "btn_language":     "🌐  LANGUE",
        "difficulty_title": "CHOISIR LA DIFFICULTÉ",
        "btn_back":         "◀  RETOUR",
        "btn_play":         "JOUER →",
        "locked":           "🔒 Nécessite",
        "questions_lbl":    "quest.",
        "mixed":            "questions mixtes",
        "hearts_lbl":       "❤ ×",
        "question_of":      "Question {} sur {}",
        "btn_exit_save":    "💰  QUITTER ET SAUVEGARDER",
        "wrong_lives":      "Faux! Vies restantes: {}",
        "game_over":        "GAME OVER",
        "lost_text":        "Vous avez perdu {}",
        "btn_restart":      "REJOUER",
        "btn_exit":         "QUITTER",
        "victory_title":    "🏆  FÉLICITATIONS!",
        "session_earned":   "Gagné cette session: {}",
        "total_balance":    "Votre solde total: {}",
        "btn_play_more":    "▶  JOUER ENCORE",
        "btn_main_menu":    "◀  MENU PRINCIPAL",
        "authors_title":    "✦  AUTEURS  ✦",
        "diff_easy":        "Facile",
        "diff_medium":      "Moyen",
        "diff_hard":        "Difficile",
        "diff_infinite":    "♾  Infini",
        "choose_language":  "CHOISIR LA LANGUE",
    },

    # ── Deutsch ──────────────────────────────────────────────
    "de": {
        "title_top":        "WER WIRD",
        "title_main":       "MILLIONÄR?",
        "balance":          "Ihr Guthaben",
        "btn_start":        "▶   STARTEN",
        "btn_authors":      "✦   AUTOREN",
        "btn_quit":         "✕   BEENDEN",
        "btn_language":     "🌐  SPRACHE",
        "difficulty_title": "SCHWIERIGKEIT WÄHLEN",
        "btn_back":         "◀  ZURÜCK",
        "btn_play":         "SPIELEN →",
        "locked":           "🔒 Benötigt",
        "questions_lbl":    "Frag.",
        "mixed":            "gemischte Fragen",
        "hearts_lbl":       "❤ ×",
        "question_of":      "Frage {} von {}",
        "btn_exit_save":    "💰  BEENDEN & SPEICHERN",
        "wrong_lives":      "Falsch! Leben übrig: {}",
        "game_over":        "GAME OVER",
        "lost_text":        "Sie verloren {}",
        "btn_restart":      "NEU STARTEN",
        "btn_exit":         "BEENDEN",
        "victory_title":    "🏆  HERZLICHEN GLÜCKWUNSCH!",
        "session_earned":   "Diese Runde verdient: {}",
        "total_balance":    "Ihr Gesamtguthaben: {}",
        "btn_play_more":    "▶  WEITER SPIELEN",
        "btn_main_menu":    "◀  HAUPTMENÜ",
        "authors_title":    "✦  AUTOREN  ✦",
        "diff_easy":        "Leicht",
        "diff_medium":      "Mittel",
        "diff_hard":        "Schwer",
        "diff_infinite":    "♾  Unendlich",
        "choose_language":  "SPRACHE WÄHLEN",
    },
}


def t(lang: str, key: str) -> str:
    """Получить перевод по языку и ключу."""
    return TRANSLATIONS.get(lang, TRANSLATIONS["ru"]).get(key, key)
